MINIMUM_DEPTH = 0.9 #m
MINIMUM_SLOP = 0.015 #m/m
MINIMUM_DIAMETER_MM = 150 #mm
MAXIMUM_VELOCITY = 5.0 #m/s

#WEIGH CALCULATION CONSTANTS
#CURRENT VALUES ARE BASED IN THE PRICE IN R$ TO PERFORM THE PIPE SERVICE IN REAL WORLD
LENGTH_FACTOR = 20.0
DEPTH_FACTOR = 50.0
DIAMETER_FACTOR = 0.5
